export interface SkunksGame {
  date: string; time: string; isHome: boolean; opponent: string; promotion?: string | null;
}

// Update this array throughout the season. Add games in chronological order.
export const SKUNKS_SCHEDULE: SkunksGame[] = [
  { date: '2026-05-29', time: '6:30 PM', isHome: true,  opponent: 'Olean Oilers',             promotion: 'Opening Night Tailgate' },
  { date: '2026-05-30', time: '6:30 PM', isHome: false, opponent: 'Olean Oilers',             promotion: null },
  { date: '2026-06-02', time: '6:30 PM', isHome: true,  opponent: 'Olean Oilers',             promotion: '$2 Night' },
  { date: '2026-06-03', time: '6:30 PM', isHome: false, opponent: 'Batavia Muckdogs',         promotion: null },
  { date: '2026-06-04', time: '6:30 PM', isHome: false, opponent: 'Newark Pilots',            promotion: null },
  { date: '2026-06-05', time: '6:30 PM', isHome: false, opponent: 'Niagara Ironbacks',        promotion: null },
  { date: '2026-06-06', time: '6:30 PM', isHome: false, opponent: 'Niagara Falls Americans',  promotion: null },
  { date: '2026-06-09', time: '11:00 AM', isHome: true, opponent: 'Olean Oilers',             promotion: 'School Kids Game' },
  { date: '2026-06-10', time: '6:30 PM', isHome: true,  opponent: 'Niagara Falls Americans',  promotion: 'Bark at the Park' },
  { date: '2026-06-11', time: '6:30 PM', isHome: false, opponent: 'Batavia Muckdogs',         promotion: null },
  { date: '2026-06-12', time: '6:30 PM', isHome: false, opponent: 'Geneva Red Wings',         promotion: null },
  { date: '2026-06-13', time: '6:30 PM', isHome: true,  opponent: 'Niagara Ironbacks',        promotion: 'Kids Carnival Night' },
  { date: '2026-06-14', time: '4:00 PM', isHome: true,  opponent: 'Elmira Pioneers',          promotion: 'Electrovaya Night' },
  { date: '2026-06-14', time: '6:30 PM', isHome: true,  opponent: 'Elmira Pioneers',          promotion: 'Electrovaya Night' },
  { date: '2026-06-16', time: '6:30 PM', isHome: false, opponent: 'Newark Pilots',            promotion: null },
  { date: '2026-06-17', time: '6:30 PM', isHome: true,  opponent: 'Olean Oilers',             promotion: 'Lawley Night' },
  { date: '2026-06-18', time: '6:30 PM', isHome: true,  opponent: 'Niagara Falls Americans',  promotion: 'First Responders Night' },
  { date: '2026-06-19', time: '6:30 PM', isHome: true,  opponent: 'Niagara Ironbacks',        promotion: 'Youth Baseball & Softball Night' },
  { date: '2026-06-23', time: '6:30 PM', isHome: false, opponent: 'Niagara Falls Americans',  promotion: null },
  { date: '2026-06-25', time: '6:30 PM', isHome: true,  opponent: 'Batavia Muckdogs',         promotion: 'JCC Free Ticket Night' },
  { date: '2026-06-27', time: '6:30 PM', isHome: true,  opponent: 'Niagara Falls Americans',  promotion: 'Kids Camp Day/Night' },
  { date: '2026-06-28', time: '4:00 PM', isHome: false, opponent: 'Auburn Doubledays',        promotion: null },
  { date: '2026-06-28', time: '7:00 PM', isHome: false, opponent: 'Auburn Doubledays',        promotion: null },
  { date: '2026-06-30', time: '6:30 PM', isHome: false, opponent: 'Olean Oilers',             promotion: null },
  { date: '2026-07-01', time: '6:30 PM', isHome: false, opponent: 'Batavia Muckdogs',         promotion: null },
  { date: '2026-07-02', time: '6:30 PM', isHome: false, opponent: 'Olean Oilers',             promotion: null },
  { date: '2026-07-03', time: '6:30 PM', isHome: true,  opponent: 'Olean Oilers',             promotion: 'Fireworks Night' },
  { date: '2026-07-04', time: '6:30 PM', isHome: false, opponent: 'Niagara Ironbacks',        promotion: null },
  { date: '2026-07-05', time: '2:05 PM', isHome: false, opponent: 'Elmira Pioneers',          promotion: null },
  { date: '2026-07-05', time: '4:30 PM', isHome: false, opponent: 'Elmira Pioneers',          promotion: null },
  { date: '2026-07-07', time: '6:30 PM', isHome: true,  opponent: 'Newark Pilots',            promotion: '$2 Night' },
  { date: '2026-07-10', time: '6:30 PM', isHome: true,  opponent: 'Batavia Muckdogs',         promotion: 'Wegmans Free Ticket Night' },
  { date: '2026-07-11', time: '6:30 PM', isHome: false, opponent: 'Geneva Red Wings',         promotion: null },
  { date: '2026-07-12', time: '4:00 PM', isHome: true,  opponent: 'Auburn Doubledays',        promotion: 'GCFCU Free Ticket Night' },
  { date: '2026-07-12', time: '6:30 PM', isHome: true,  opponent: 'Auburn Doubledays',        promotion: 'GCFCU Free Ticket Night' },
  { date: '2026-07-13', time: '6:30 PM', isHome: false, opponent: 'Batavia Muckdogs',         promotion: null },
  { date: '2026-07-15', time: '6:30 PM', isHome: true,  opponent: 'Batavia Muckdogs',         promotion: 'Superhero Night' },
  { date: '2026-07-16', time: '6:30 PM', isHome: false, opponent: 'Niagara Falls Americans',  promotion: null },
  { date: '2026-07-17', time: '6:30 PM', isHome: true,  opponent: 'Newark Pilots',            promotion: 'Strike Out Cancer Night' },
  { date: '2026-07-19', time: '4:00 PM', isHome: true,  opponent: 'Geneva Red Wings',         promotion: 'United Way Night' },
  { date: '2026-07-21', time: '6:30 PM', isHome: true,  opponent: 'Niagara Ironbacks',        promotion: '$2 Night' },
  { date: '2026-07-23', time: '6:30 PM', isHome: false, opponent: 'Olean Oilers',             promotion: null },
  { date: '2026-07-24', time: '6:30 PM', isHome: false, opponent: 'Olean Oilers',             promotion: null },
  { date: '2026-07-25', time: '6:30 PM', isHome: true,  opponent: 'Geneva Red Wings',         promotion: 'Xmas in July' },
];
